[versions]
# Kotlin
kotlin = "2.2.21"
aether = "0.2.0.0"

# Kotlinx
kotlinxCoroutines = "1.10.2"
kotlinxCoroutinesJs = "1.10.2"
kotlinxCoroutinesJdk8 = "1.10.2"
kotlinxSerialization = "1.9.0"
kotlinxHtml = "0.12.0"
kotlinxDatetime = "0.6.2"
atomicfu = "0.29.0"
kotlinxBrowser = "0.5.0"

# Kotlin Wrappers
kotlinWrappersBase = "2025.10.14"
kotlinWrappersExtensions = "1.0.1-pre.823"
kotlinReactDom = "2025.10.14-19.2.0"

# NPM
coreJs = "3.46.0"
codemirror = "6.0.1"
chartJs = "4.4.1"
markdownIt = "14.0.0"
highlightJs = "11.9.0"

# Quarkus
quarkus = "3.15.7"
quarkusJvm = "3.15.7"

# Ktor
ktor = "3.3.1"

# Spring Boot
springBoot = "3.5.7"
springBootJvm = "3.5.7"
reactorKotlin = "1.2.4"
reactorKotlinJvm = "1.2.4"
springFramework = "6.2.12"
blockhound = "1.0.8.RELEASE"
reactorCore = "3.7.12"

# CLI
clikt = "5.0.3"
shadowJar = "8.1.1"
graalvm = "0.11.2"
kaml = "0.102.0"
commonsCompress = "1.28.0"
commonsIo = "2.20.0"

# Testing
kotest = "5.9.1"
jsoup = "1.18.1"
binaryCompatibilityValidator = "0.16.3"
flexmark = "0.64.8"

[libraries]
aether-core = { module = "codes.yousef.aether:aether-core", version.ref = "aether" }
# Kotlin
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-stdlib-js = { module = "org.jetbrains.kotlin:kotlin-stdlib-js", version.ref = "kotlin" }
kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Kotlinx
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinxCoroutinesJdk8" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "kotlinxCoroutinesJs" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json-jvm = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json-js = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-js", version.ref = "kotlinxSerialization" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinxHtml" }
kotlinx-html-jvm = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinxHtml" }
kotlinx-html-js = { module = "org.jetbrains.kotlinx:kotlinx-html-js", version.ref = "kotlinxHtml" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }

# Kotlin Wrappers
kotlin-js = { module = "org.jetbrains.kotlin-wrappers:kotlin-js", version.ref = "kotlinWrappersBase" }
kotlin-extensions = { module = "org.jetbrains.kotlin-wrappers:kotlin-extensions", version.ref = "kotlinWrappersExtensions" }
kotlin-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlinWrappersBase" }
kotlin-react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom", version.ref = "kotlinReactDom" }

# NPM dependencies are handled differently - removing this entry

# Quarkus for JVM
quarkus-core-jvm = { module = "io.quarkus:quarkus-core", version.ref = "quarkusJvm" }
quarkus-qute-jvm = { module = "io.quarkus:quarkus-qute", version.ref = "quarkusJvm" }
quarkus-kotlin-jvm = { module = "io.quarkus:quarkus-kotlin", version.ref = "quarkusJvm" }
quarkus-vertx-http-jvm = { module = "io.quarkus:quarkus-vertx-http", version.ref = "quarkusJvm" }
quarkus-resteasy-reactive-jvm = { module = "io.quarkus:quarkus-rest", version.ref = "quarkusJvm" }
quarkus-resteasy-reactive-jackson-jvm = { module = "io.quarkus:quarkus-rest-jackson", version.ref = "quarkusJvm" }
quarkus-websockets-jvm = { module = "io.quarkus:quarkus-websockets", version.ref = "quarkusJvm" }
quarkus-arc-jvm = { module = "io.quarkus:quarkus-arc", version.ref = "quarkusJvm" }
quarkus-core-deployment-jvm = { module = "io.quarkus:quarkus-core-deployment", version.ref = "quarkusJvm" }
quarkus-arc-deployment-jvm = { module = "io.quarkus:quarkus-arc-deployment", version.ref = "quarkusJvm" }
quarkus-security-deployment-jvm = { module = "io.quarkus:quarkus-security-deployment", version.ref = "quarkusJvm" }

# Quarkus for Integration
quarkus-core = { module = "io.quarkus:quarkus-core", version.ref = "quarkus" }
quarkus-qute = { module = "io.quarkus:quarkus-qute", version.ref = "quarkus" }
quarkus-kotlin = { module = "io.quarkus:quarkus-kotlin", version.ref = "quarkus" }
quarkus-vertx-http = { module = "io.quarkus:quarkus-vertx-http", version.ref = "quarkus" }
quarkus-resteasy-reactive = { module = "io.quarkus:quarkus-rest", version.ref = "quarkus" }
quarkus-resteasy-reactive-jackson = { module = "io.quarkus:quarkus-rest-jackson", version.ref = "quarkus" }
quarkus-websockets = { module = "io.quarkus:quarkus-websockets", version.ref = "quarkus" }
quarkus-arc = { module = "io.quarkus:quarkus-arc", version.ref = "quarkus" }
quarkus-core-deployment = { module = "io.quarkus:quarkus-core-deployment", version.ref = "quarkus" }
quarkus-arc-deployment = { module = "io.quarkus:quarkus-arc-deployment", version.ref = "quarkus" }
quarkus-security-deployment = { module = "io.quarkus:quarkus-security-deployment", version.ref = "quarkus" }

# Ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

# Spring Boot for JVM
spring-boot-starter-web-jvm = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBootJvm" }
spring-boot-starter-thymeleaf-jvm = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "springBootJvm" }
spring-boot-starter-webflux-jvm = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springBootJvm" }
reactor-kotlin-extensions-jvm = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version.ref = "reactorKotlinJvm" }

# Spring Boot for Integration
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "springBoot" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springBoot" }
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version.ref = "reactorKotlin" }
spring-test = { module = "org.springframework:spring-test", version.ref = "springFramework" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactorCore" }
blockhound = { module = "io.projectreactor.tools:blockhound", version.ref = "blockhound" }

# CLI
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }

# Testing
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
flexmark-all = { module = "com.vladsch.flexmark:flexmark-all", version.ref = "flexmark" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
shadow-jar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
graalvm-native-image = { id = "org.graalvm.buildtools.native", version.ref = "graalvm" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
